export const data = [
    {
        "id":1,
        "path":"/assets/images/story1.png" 
    },
    {
        "id":2,
        "path":"/assets/images/story2.png" 
    },
    {
        "id":3,
        "path":"/assets/images/story3.png" 
    },
    {
        "id":4,
        "path":"/assets/images/story4.png" 
    },
    {
        "id":5,
        "path":"/assets/images/story5.png" 
    },
]

export const data1=[
    {
        "id":1,
        "path":"/assets/images/story1.png" 
    },
    {
        "id":2,
        "path":"/assets/images/story2.png" 
    },
    {
        "id":3,
        "path":"/assets/images/story5.png" 
    },
    {
        "id":4,
        "path":"/assets/images/story3.png" 
    },
    {
        "id":5,
        "path":"/assets/images/story4.png" 
    },
]